-- Signed-in authorization regression. ALL_PASSED deliberately rolls back all fixtures.
DO $$
DECLARE
 a uuid; m uuid; u uuid; c uuid; other_c uuid; p uuid; other_p uuid; comment_id uuid; n int; denied boolean;
BEGIN
 SELECT user_id INTO a FROM public.user_roles WHERE role='admin' LIMIT 1;
 SELECT user_id INTO m FROM public.profiles WHERE NOT public.has_role(user_id,'admin') ORDER BY created_at LIMIT 1;
 SELECT user_id INTO u FROM public.profiles WHERE NOT public.has_role(user_id,'admin') AND user_id<>m ORDER BY created_at LIMIT 1;
 IF a IS NULL OR m IS NULL OR u IS NULL THEN RAISE EXCEPTION 'SETUP: need admin and two users'; END IF;
 INSERT INTO public.communities(name) VALUES ('__moderation_test_' || gen_random_uuid()) RETURNING id INTO c;
 INSERT INTO public.communities(name) VALUES ('__moderation_other_' || gen_random_uuid()) RETURNING id INTO other_c;
 INSERT INTO public.community_members(community_id,user_id) VALUES (c,u),(other_c,m);
 INSERT INTO public.community_posts(community_id,user_id,content) VALUES (c,a,'test') RETURNING id INTO p;
 INSERT INTO public.community_posts(community_id,user_id,content) VALUES (other_c,a,'test') RETURNING id INTO other_p;
 INSERT INTO public.community_post_comments(post_id,user_id,content) VALUES (p,a,'test') RETURNING id INTO comment_id;
 PERFORM set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true);
 SET LOCAL ROLE authenticated;
 denied:=false;
 BEGIN PERFORM public.set_community_moderator(c,u,true); EXCEPTION WHEN insufficient_privilege THEN denied:=true; END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL: regular user appointed moderator'; END IF;
 denied:=false;
 BEGIN INSERT INTO public.community_moderators(community_id,user_id,appointed_by) VALUES(c,u,u); EXCEPTION WHEN insufficient_privilege THEN denied:=true; END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL: direct self-promotion'; END IF;
 denied:=false;
 BEGIN INSERT INTO public.communities(name) VALUES ('__forbidden'); EXCEPTION WHEN insufficient_privilege THEN denied:=true; END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL: regular user created community'; END IF;
 UPDATE public.communities SET cover_url='forbidden' WHERE id=c;
 GET DIAGNOSTICS n=ROW_COUNT;
 IF n<>0 THEN RAISE EXCEPTION 'FAIL: regular user edited profile'; END IF;
 DELETE FROM public.community_posts WHERE id=p;
 GET DIAGNOSTICS n=ROW_COUNT;
 IF n<>0 THEN RAISE EXCEPTION 'FAIL: regular user deleted another author post'; END IF;
 RESET ROLE;
 PERFORM set_config('request.jwt.claims',json_build_object('sub',a,'role','authenticated')::text,true);
 SET LOCAL ROLE authenticated;
 PERFORM public.set_community_moderator(c,m,true);
 RESET ROLE;
 PERFORM set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true);
 SET LOCAL ROLE authenticated;
 IF NOT public.can_moderate_community(c) OR public.can_moderate_community(other_c) THEN RAISE EXCEPTION 'FAIL: moderator scope'; END IF;
 UPDATE public.communities SET cover_url='forbidden' WHERE id=c;
 GET DIAGNOSTICS n=ROW_COUNT;
 IF n<>0 THEN RAISE EXCEPTION 'FAIL: moderator edited profile'; END IF;
 denied:=false;
 BEGIN PERFORM public.set_community_moderator(c,u,true); EXCEPTION WHEN insufficient_privilege THEN denied:=true; END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL: moderator appointed another moderator'; END IF;
 DELETE FROM public.community_posts WHERE id=other_p;
 GET DIAGNOSTICS n=ROW_COUNT;
 IF n<>0 THEN RAISE EXCEPTION 'FAIL: cross-community deletion'; END IF;
 DELETE FROM public.community_post_comments WHERE id=comment_id;
 GET DIAGNOSTICS n=ROW_COUNT;
 IF n<>1 THEN RAISE EXCEPTION 'FAIL: moderator comment deletion'; END IF;
 DELETE FROM public.community_posts WHERE id=p;
 GET DIAGNOSTICS n=ROW_COUNT;
 IF n<>1 THEN RAISE EXCEPTION 'FAIL: moderator post deletion'; END IF;
 RESET ROLE;
 PERFORM set_config('request.jwt.claims',json_build_object('sub',a,'role','authenticated')::text,true);
 SET LOCAL ROLE authenticated;
 PERFORM public.set_community_moderator(c,m,false);
 DELETE FROM public.community_posts WHERE id=other_p;
 GET DIAGNOSTICS n=ROW_COUNT;
 IF n<>1 THEN RAISE EXCEPTION 'FAIL: admin moderation'; END IF;
 RESET ROLE;
 PERFORM set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true);
 SET LOCAL ROLE authenticated;
 IF public.can_moderate_community(c) THEN RAISE EXCEPTION 'FAIL: revoked moderator retains access'; END IF;
 RESET ROLE;
 RAISE EXCEPTION 'ALL_PASSED';
END $$;